services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    working_dir: /app
    depends_on:
      - postgres
      - localstack
    restart: always
    command: npm start

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Assuming Vite or similar; update if needed
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true # Fixes file watching in Docker
    command: npm run dev
    depends_on:
      - backend

  localstack:
    build:
      context: .
      dockerfile: Dockerfile.localstack
    container_name: localstack
    ports:
      - "4566:4566"
    env_file:
      - ./backend/.env
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack-data:/var/lib/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  localstack-data:
  pgdata:
